// Generated by CoffeeScript 1.10.0
var Dredd, DreddCommand, configUtils, console, exec, exports, fs, interactiveConfig, optimist, parsePackageJson, path, version;

path = require('path');

optimist = require('optimist');

console = require('console');

fs = require('fs');

exec = require('child_process').exec;

parsePackageJson = require('./parse-package-json');

Dredd = require('./dredd');

interactiveConfig = require('./interactive-config');

configUtils = require('./config-utils');

version = parsePackageJson(path.join(__dirname, '../package.json'));

DreddCommand = (function() {
  function DreddCommand(options, cb) {
    if (options == null) {
      options = {};
    }
    this.cb = cb;
    if (!(this instanceof DreddCommand)) {
      return new DreddCommand(options, this.cb);
    }
    this.exit = options.exit, this.custom = options.custom;
    if (this.custom == null) {
      this.custom = {};
    }
    if (!this.custom.cwd || typeof this.custom.cwd !== 'string') {
      this.custom.cwd = process.cwd();
    }
    if (!this.custom.argv || !Array.isArray(this.custom.argv)) {
      this.custom.argv = [];
    }
    this.finished = false;
  }

  DreddCommand.prototype.setOptimistArgv = function() {
    this.optimist = optimist(this.custom['argv'], this.custom['cwd']);
    this.cliArgv = this.optimist.argv;
    this.optimist.usage("Usage:\n  $ dredd init\n\nOr:\n  $ dredd <path or URL to blueprint> <api_endpoint> [OPTIONS]\n\nExample:\n  $ dredd ./apiary.md http://localhost:3000 --dry-run").options(Dredd.options).wrap(80);
    return this.argv = this.optimist.argv;
  };

  DreddCommand.prototype.setExitOrCallback = function() {
    if (!this.cb) {
      if (this.exit && (this.exit === process.exit)) {
        this.sigIntEventAdd = true;
      }
      if (this.exit) {
        return this._processExit = (function(code) {
          this.finished = true;
          if (this.serverProcess != null) {
            this.serverProcess.kill('SIGKILL');
          }
          return this.exit(code);
        }).bind(this);
      } else {
        return this._processExit = (function(code) {
          if (this.serverProcess != null) {
            this.serverProcess.kill('SIGKILL');
          }
          return process.exit(code);
        }).bind(this);
      }
    } else {
      return this._processExit = (function(code) {
        this.finished = true;
        if (this.sigIntEventAdded) {
          process.removeEventListener('SIGINT', this.commandSigInt);
        }
        this.cb(code);
        return this;
      }).bind(this);
    }
  };

  DreddCommand.prototype.moveBlueprintArgToPath = function() {
    if (!Array.isArray(this.argv['path'])) {
      return this.argv['path'] = this.argv['p'] = [this.argv['path']];
    }
  };

  DreddCommand.prototype.checkRequiredArgs = function() {
    var argError;
    argError = false;
    if (this.argv._[0] == null) {
      console.error("\nError: Must specify path to blueprint file.");
      argError = true;
    }
    if (this.argv._[1] == null) {
      console.error("\nError: Must specify api endpoint.");
      argError = true;
    }
    if (argError) {
      console.error("\n");
      this.optimist.showHelp(console.error);
      return this._processExit(1);
    }
  };

  DreddCommand.prototype.runExitingActions = function() {
    if (this.argv["_"][0] === "init" || this.argv.init === true) {
      this.finished = true;
      return interactiveConfig.run(this.argv, (function(_this) {
        return function(config) {
          configUtils.save(config);
          console.log("");
          console.log("Configuration saved to dredd.yml");
          console.log("");
          if (config['language'] === "nodejs") {
            console.log("Run test now, with:");
          } else {
            console.log("Install hooks handler and run Dredd test with:");
          }
          console.log("");
          if (config['language'] === 'ruby') {
            console.log("  $ gem install dredd_hooks");
          } else if (config['language'] === 'python') {
            console.log("  $ pip install dredd_hooks");
          }
          console.log("  $ dredd");
          console.log("");
          return _this._processExit(0);
        };
      })(this));
    } else if (this.argv.help === true) {
      this.optimist.showHelp(console.error);
      return this._processExit(0);
    } else if (this.argv.version === true) {
      console.log(version);
      return this._processExit(0);
    }
  };

  DreddCommand.prototype.loadDreddFile = function() {
    var key, ref, results, value;
    if (fs.existsSync('./dredd.yml')) {
      console.log('Configuration dredd.yml found, ignoring other arguments.');
      this.argv = configUtils.load();
    }
    ref = this.cliArgv;
    results = [];
    for (key in ref) {
      value = ref[key];
      if (key !== "_" && key !== "$0") {
        results.push(this.argv[key] = value);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  DreddCommand.prototype.parseCustomConfig = function() {
    return this.argv.custom = configUtils.parseCustom(this.argv.custom);
  };

  DreddCommand.prototype.runServerAndThenDredd = function(callback) {
    var waitMilis, waitSecs;
    if (this.argv['server'] == null) {
      return this.runDredd(this.dreddInstance);
    } else {
      this.serverProcess = exec(this.argv['server']);
      console.log("Starting server with command: " + this.argv['server']);
      this.serverProcess.stdout.setEncoding('utf8');
      this.serverProcess.stdout.on('data', function(data) {
        return process.stdout.write(data.toString());
      });
      this.serverProcess.stderr.setEncoding('utf8');
      this.serverProcess.stderr.on('data', function(data) {
        return process.stdout.write(data.toString());
      });
      this.serverProcess.on('error', (function(_this) {
        return function(error) {
          console.log(error);
          console.log("Server command failed, exitting...");
          return _this._processExit(2);
        };
      })(this));
      process.on('beforeExit', (function(_this) {
        return function() {
          if (_this.serverProcess != null) {
            return _this.serverProcess.kill('SIGKILL');
          }
        };
      })(this));
      process.on('exit', (function(_this) {
        return function() {
          if (_this.serverProcess != null) {
            return _this.serverProcess.kill('SIGKILL');
          }
        };
      })(this));
      waitSecs = parseInt(this.argv['server-wait'], 10);
      waitMilis = waitSecs * 1000;
      console.log("Waiting " + waitSecs + " seconds for server command to start...");
      return this.wait = setTimeout((function(_this) {
        return function() {
          return _this.runDredd(_this.dreddInstance);
        };
      })(this), waitMilis);
    }
  };

  DreddCommand.prototype.run = function() {
    var configurationForDredd, e, error1, i, len, ref, task;
    ref = [this.setOptimistArgv, this.setExitOrCallback, this.parseCustomConfig, this.runExitingActions, this.loadDreddFile, this.checkRequiredArgs, this.moveBlueprintArgToPath];
    for (i = 0, len = ref.length; i < len; i++) {
      task = ref[i];
      task.call(this);
      if (this.finished) {
        return;
      }
    }
    configurationForDredd = this.initConfig();
    this.dreddInstance = this.initDredd(configurationForDredd);
    try {
      this.runServerAndThenDredd();
    } catch (error1) {
      e = error1;
      console.log(e.message);
      console.log(e.stack);
      this._processExit(2);
    }
  };

  DreddCommand.prototype.lastArgvIsApiEndpoint = function() {
    this.server = this.argv._[this.argv._.length - 1];
    this.argv._.splice(this.argv._.length - 1, 1);
    return this;
  };

  DreddCommand.prototype.takeRestOfParamsAsPath = function() {
    this.argv['p'] = this.argv['path'] = this.argv['path'].concat(this.argv._);
    return this;
  };

  DreddCommand.prototype.initConfig = function() {
    var base, configuration;
    this.lastArgvIsApiEndpoint().takeRestOfParamsAsPath();
    configuration = {
      'server': this.server,
      'options': this.argv
    };
    if ((base = configuration.options).path == null) {
      base.path = [];
    }
    configuration.options.path.push(this.argv._[0]);
    configuration.custom = this.custom;
    return configuration;
  };

  DreddCommand.prototype.initDredd = function(configuration) {
    var dredd;
    dredd = new Dredd(configuration);
    return dredd;
  };

  DreddCommand.prototype.commandSigInt = function() {
    console.log("\nShutting down from SIGINT (Ctrl-C)");
    return this.dreddInstance.transactionsComplete((function(_this) {
      return function() {
        return _this._processExit(0);
      };
    })(this));
  };

  DreddCommand.prototype.runDredd = function(dreddInstance) {
    if (this.sigIntEventAdd) {
      this.sigIntEventAdded = !(this.sigIntEventAdd = false);
      process.on('SIGINT', this.commandSigInt);
    }
    dreddInstance.run((function(_this) {
      return function(error, stats) {
        if (error) {
          if (error.message) {
            console.error(error.message);
          }
          if (error.stack) {
            console.error(error.stack);
          }
          return _this._processExit(1);
        }
        if ((stats.failures + stats.errors) > 0) {
          _this._processExit(1);
        } else {
          _this._processExit(0);
        }
      };
    })(this));
    return this;
  };

  return DreddCommand;

})();

exports = module.exports = DreddCommand;
