#!/bin/sh
# Usage:
# ./scripts/cov [reporter]
#
# Example:
# ./scripts/cov html-cov > cov.html

COV=./node_modules/coffee-coverage/bin/coffeecoverage
MOCHA=./node_modules/.bin/mocha

REPORTER=$1
echo "Using Mocha reporter: $REPORTER" 1>&2

# Cleanup
rm -rf ./src-cov

# Creating directory with instrumented JS code
$COV --exclude node_modules,.git,test --path=relative . ./src-cov 1>&2
cp ./package.json ./src-cov
cp -r ./test ./src-cov/test
cp -r ./bin ./src-cov/bin

# Replacing 'lib' with 'src' in require path in ./bin/dredd
sed -e 's/\/lib\/dredd-command/\/src\/dredd-command/g' ./src-cov/bin/dredd > ./src-cov/bin/dredd.tmp
mv ./src-cov/bin/dredd.tmp ./src-cov/bin/dredd
chmod +x ./src-cov/bin/dredd

# Testing
find ./src-cov/test/ -name '*-test.coffee' | xargs "$MOCHA" \
  --compilers='coffee:coffee-script/register' \
  --reporter="$REPORTER" \
  --timeout=120000 \
  --recursive

# Cleanup
rm -rf ./src-cov
